apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project:  default
  source:
    repoURL:  https://github.com/mshoaibnoor/argocd-ops.git
    targetRevision: HEAD
    path: nginx/overlays/dev
  destination:
    server:  https://kubernetes.default.svc
    namespace:  ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true