apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: grafana-k8s-monitoring
    namespace: argocd
finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: ''
    chart: k8s-monitoring
    helm:
        values: |-
            cluster:
                name: "<cluster-name>"
            externalServices:
                prometheus:
                    host: "{prometheus-url}"
                    basicAuth:
                        username: "{prometheus-username}"
                        password: "{cloud-access-token}"
                loki:
                    host: "{loki-url}"
                    basicAuth:
                        username: "{loki-username}"
                        password: "{cloud-access-token}"
            opencost:
                opencost:
                    exporter:
                        defaultClusterId: "<cluster-name>"
                    prometheus:
                        external:
                            url: "{prometheus-url}/api/prom"
sources: []
project: default
syncPolicy:
    automated:
        prune: true
        selfHeal: true
    retry:
        limit: 2
        backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
    syncOptions:
        - CreateNamespace=true
