apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project:  default
  source:
    repoURL:  https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
    chart:  ingress-nginx
  destination:
    server:  https://kubernetes.default.svc
    namespace:  ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true